export const ADD_PROFILE = "ADD_PROFILE";
export const DELETE_PROFILE = "DELETE_PROFILE";
export const CHANGE_PROFILE = "CHANGE_PROFILE";
export const FETCH_PROFILES = "FETCH_PROFILES";
export const FILTER_PROFILES = "FILTER_PROFILES";
export const FETCH_TECHNOLOGIES = "FETCH_TECHNOLOGIES";
export const FETCH_PROJECTS = "FETCH_PROJECTS";
export const CREATE_PROFILE = "CREATE_PROFILE";
